groups:
- name: RAM
  rules:
  - alert: low_ram
    expr: sum(node_memory_MemFree_bytes) / sum(node_memory_MemTotal_bytes) < 0.20
    for: 1m
    labels:
      severity: "page"
    annotations:
      summary: "RAM usage has surpassed 80%"
  
  - alert: very_low_ram
    expr: sum(node_memory_MemFree_bytes) / sum(node_memory_MemTotal_bytes) < 0.05
    for: 1m
    labels:
      severity: "critical"
    annotations:
      summary: "RAM usage has surpassed 95%"

groups:
- name: Temperature
  rules:
  - alert: CPU1_high_temp
    expr: avg(ipmi_cpu_temp1) > 35
    for: 5m
    labels:
      severity: "page"
    annotations:
      summary: "CPU 1 Temperature is above 35 C"
    
  - alert: CPU2_high_temp
    expr: avg(ipmi_cpu_temp2) > 35
    for: 5m
    labels:
      severity: "page"
    annotations:
      summary: "CPU 2 Temperature is above 35 C"

